permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "My Own Heaven"
email: "loumymoon@gmail.com"
description: "Developer"
github_username:  "SaddestMoon"
swiftype_searchId: "FGzNPt9shNmxy6yAs3rf"
disqus_shortname: "fornever-1"




url: "http://blog.fornever.cn"
imgrepo: "http://blog.fornever.cn/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

